--USE master 
--GO
--DROP DATABASE BDJURIDICO			
CREATE DATABASE BDJURIDICO

USE BDJURIDICO

CREATE TABLE ESTADO (
  ESTID INT IDENTITY(1,1) PRIMARY KEY,
  ESTDESCRICAO VARCHAR(100) NOT NULL,
  ESTSIGLA VARCHAR(2) NOT NULL UNIQUE
);

SELECT * FROM ESTADO 

--INSERT ESTADO (ESTDESCRICAO, ESTSIGLA) VALUES ('SERGIPE','SE')
INSERT ESTADO (ESTDESCRICAO,ESTSIGLA) VALUES ('SÃO PAULO','SP')
INSERT ESTADO (ESTDESCRICAO,ESTSIGLA) VALUES ('RORAIMA','RR')
INSERT ESTADO VALUES ('ACRE', 'AC')
INSERT ESTADO VALUES ('BAHIA', 'BA')

----FILTRAR
--SELECT * FROM ESTADO WHERE ESTID=2


--UPDATE ESTADO 
--SET ESTDESCRICAO='SAO PAULO', ESTSIGLA='PP'
--WHERE ESTID=2

--DELETE ESTADO 
--WHERE ESTID=4

----FILTROS
--SELECT * FROM ESTADO 
--WHERE ESTDESCRICAO LIKE 'S%'

--SELECT * FROM ESTADO 
--WHERE ESTDESCRICAO LIKE '%S'

--SELECT * FROM ESTADO 
--WHERE ESTDESCRICAO LIKE '$Sao%'

--SELECT * FROM ESTADO 
--WHERE ESTID >3


--SELECT * FROM ESTADO
--WHERE ESTID=3 OR ESTID=5

--SELECT * FROM ESTADO
--WHERE ESTID IN (3,4)

--SELECT ESTDESCRICAO, ESTSIGLA FROM ESTADO
--WHERE ESTID IN (3,4)

--SELECT ESTDESCRICAO AS 'DESCRICAO', ESTSIGLA AS 'SIGLA' FROM ESTADO
--WHERE ESTID IN (3,4)

--SELECT * FROM ESTADO 
--WHERE ESTID !=1

CREATE TABLE CIDADE (
  CIDID INT IDENTITY (1,1)
  CIDDESCRICAO VARCHAR (1,1) PRIMARY KEY,
  ESTDESCRICAO VARCHAR(100) NOT NULL,
  ESTID INT NOT NULL REFERENCES ESTADO(ESTID)
  )
  GO
  SELECT * FROM ESTADO 
  SELECT * FROM CIDADE 
  INSERT CIDADE VALUES ('ESTANCIA',1)
  
  
  CREATE TABLE TIPODOCUMENTO(
  TIPID INT IDENTITY (1,1) PRIMARY KEY ,
  TIPDESCRICAO VARCHAR(100) NOT NULL UNIQUE,
  )


  CREATE TABLE PESSOA(
  PESID INT IDENTITY (1,1) PRIMARY KEY,
  PESNOME VARCHAR (200) NOT NULL,
  PESCPF VARCHAR (100) NOT NULL,
  PESENDEREÇO VARCHAR (100) NOT NULL,
  )
  SELECT * FROM PESSOA 

  






